#pragma once
#define MAX_Y_CORDINATE 2
#define MIN_Y_CORDINATE 0
#define MAX_X_CORDINATE 2
#define MIN_X_CORDINATE 0

enum WINNER {
	PLUS, CIRC, NONE, NOT_FINISHED
};
enum PLAYER_TYPE {
	CROSS, CIRCLE
};
enum State {
	CIRCLE_OFF = 0, CIRCLE_ON, CROSS_OFF, CROSS_ON, FREE_OFF, FREE_ON,
	END_OF_STATES
};